version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Test123
      POSTGRES_DB: demo
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: